---
version: '3'

tasks:
  default:
    desc: 'Show available tasks'
    cmds:
      - task --list

  a2a:download-schema:
    desc: 'Download the latest A2A schema and convert to YAML'
    cmds:
      - curl -o schema.yaml https://raw.githubusercontent.com/inference-gateway/schemas/refs/heads/main/a2a/a2a-schema.yaml

  a2a:generate-types:
    desc: 'Generate the Golang ADK types from the A2A schema'
    cmds:
      - go run github.com/inference-gateway/tools/cmd/generator@v0.1.1 -generator jsonrpc -package adk schema.yaml adk/generated_types.go

  tidy:
    desc: 'Tidy all Go modules'
    cmds:
      - find . -name 'go.mod' -execdir go mod tidy \;

  lint:
    desc: 'Run Go static analysis and linting'
    cmds:
      - golangci-lint run

  build:
    desc: 'Build the Go application'
    vars:
      AGENT_NAME: '{{.AGENT_NAME | default "helloworld-agent"}}'
      AGENT_DESCRIPTION: '{{.AGENT_DESCRIPTION | default "A simple greeting agent that provides personalized greetings using the A2A protocol"}}'
      AGENT_VERSION: '{{.AGENT_VERSION | default "1.0.0"}}'
    cmds:
      - go build -ldflags="-X github.com/inference-gateway/a2a/adk/server.BuildAgentName={{.AGENT_NAME}} -X 'github.com/inference-gateway/a2a/adk/server.BuildAgentDescription={{.AGENT_DESCRIPTION}}' -X github.com/inference-gateway/a2a/adk/server.BuildAgentVersion={{.AGENT_VERSION}}" -o bin/app .

  build:with-metadata:
    desc: 'Build the Go application with custom metadata'
    vars:
      AGENT_NAME: '{{.AGENT_NAME | default "helloworld-agent"}}'
      AGENT_DESCRIPTION: '{{.AGENT_DESCRIPTION | default "A simple greeting agent that provides personalized greetings using the A2A protocol"}}'
      AGENT_VERSION: '{{.AGENT_VERSION | default "1.0.0"}}'
    cmds:
      - go build -ldflags="-X github.com/inference-gateway/a2a/adk/server.BuildAgentName={{.AGENT_NAME}} -X 'github.com/inference-gateway/a2a/adk/server.BuildAgentDescription={{.AGENT_DESCRIPTION}}' -X github.com/inference-gateway/a2a/adk/server.BuildAgentVersion={{.AGENT_VERSION}}" -o bin/app .

  test:
    desc: 'Run tests'
    cmds:
      - go test -v -cover ./...

  clean:
    desc: 'Clean up'
    cmds:
      - rm -rf bin

  clean:mocks:
    desc: 'Clean up generated mocks'
    cmds:
      - rm -rf adk/server/mocks/*.go

  generate:mocks:
    desc: 'Generate all mocks using counterfeiter'
    cmds:
      - task: generate:mock:a2a-client
      - task: generate:mock:a2a-server
      - task: generate:mock:a2a-server-builder
      - task: generate:mock:agent-builder
      - task: generate:mock:task-handler
      - task: generate:mock:message-handler
      - task: generate:mock:task-manager
      - task: generate:mock:response-sender
      - task: generate:mock:oidc-authenticator
      - task: generate:mock:task-result-processor
      - task: generate:mock:telemetry
      - task: generate:mock:opentelemetry
      - task: generate:mock:llm-client

  generate:mocks:clean:
    desc: 'Clean and regenerate all mocks'
    cmds:
      - task: clean:mocks
      - task: generate:mocks

  generate:mock:a2a-client:
    desc: 'Generate mock for A2AClient interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/client/mocks/fake_a2a_client.go adk/client A2AClient

  generate:mock:a2a-server:
    desc: 'Generate mock for A2AServer interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/server/mocks/fake_a2a_server.go adk/server A2AServer

  generate:mock:a2a-server-builder:
    desc: 'Generate mock for A2AServerBuilder interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/server/mocks/fake_a2a_server_builder.go adk/server A2AServerBuilder

  generate:mock:task-handler:
    desc: 'Generate mock for TaskHandler interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/server/mocks/fake_task_handler.go adk/server TaskHandler

  generate:mock:message-handler:
    desc: 'Generate mock for MessageHandler interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/server/mocks/fake_message_handler.go adk/server MessageHandler

  generate:mock:task-manager:
    desc: 'Generate mock for TaskManager interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/server/mocks/fake_task_manager.go adk/server TaskManager

  generate:mock:response-sender:
    desc: 'Generate mock for ResponseSender interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/server/mocks/fake_response_sender.go adk/server ResponseSender

  generate:mock:tools-provider:
    desc: 'Generate mock for ToolsProvider interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/server/mocks/fake_tools_provider.go adk/server ToolsProvider

  generate:mock:task-result-processor:
    desc: 'Generate mock for TaskResultProcessor interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/server/mocks/fake_task_result_processor.go adk/server TaskResultProcessor

  generate:mock:telemetry:
    desc: 'Generate mock for Telemetry interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/server/mocks/fake_telemetry.go adk/server/middlewares Telemetry

  generate:mock:oidc-authenticator:
    desc: 'Generate mock for OIDCAuthenticator interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/server/mocks/fake_oidc_authenticator.go adk/server/middlewares OIDCAuthenticator

  generate:mock:opentelemetry:
    desc: 'Generate mock for OpenTelemetry interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/server/mocks/fake_opentelemetry.go adk/server/otel OpenTelemetry

  generate:mock:llm-client:
    desc: 'Generate mock for LLMClient interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/server/mocks/fake_llm_client.go adk/server LLMClient

  generate:mock:agent-builder:
    desc: 'Generate mock for AgentBuilder interface'
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o adk/server/mocks/fake_agent_builder.go adk/server AgentBuilder
